# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(default='client_logos/none/no-logo.png', upload_to='client_logos/')),
            ],
        ),
    ]
