# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 07:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20171119_0759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('unit_type', models.CharField(choices=[('cpc', 'CPC'), ('cpm', 'CPM'), ('cpv', 'CPV')], default='cpc', max_length=3)),
                ('units', models.IntegerField(default=0)),
                ('budget', models.IntegerField(default=0)),
                ('budget_spent', models.IntegerField(default=0)),
                ('units_delivered', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
                ('medium_name', models.CharField(default='Name', max_length=50)),
                ('logo', models.ImageField(default='publisher_logos/none/no-logo.png', upload_to='publisher_logos/')),
            ],
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='name',
            new_name='campaign_name',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='budget_spent',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='unit_type',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='units',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='units_delivered',
        ),
        migrations.AddField(
            model_name='placement',
            name='campaign_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Campaign'),
        ),
        migrations.AddField(
            model_name='placement',
            name='medium_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Publisher'),
        ),
    ]
