# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20171119_0817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placement',
            old_name='medium_name',
            new_name='publisher_name',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='medium_name',
        ),
        migrations.AddField(
            model_name='publisher',
            name='publisher_name',
            field=models.CharField(default='Nazwa', max_length=50),
        ),
    ]
