# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20171119_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='publisher_name',
            field=models.CharField(max_length=50),
        ),
    ]
