# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20171119_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='diff',
            field=models.NullBooleanField(default=False),
        ),
    ]
