# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_placement_diff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='diff',
            field=models.BooleanField(default=False),
        ),
    ]
